name: Arduino Library Checks
on: [push, pull_request]
jobs:
  ArduinoLintjob:
    name: Run Arduino Lint
    env:
      compliance: strict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1

  arduino_ci:
    name: Build_Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Arduino-CI/action@stable-1.x
        env:
          EXPECT_EXAMPLES: true
#          EXPECT_UNITTESTS: true